# Site settings
title: MSetzu
description: >- # this means to ignore newlines until "baseurl:"
  Exploit data to get insight.
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
author:
  email: m.setzu@outlook.com
  github_username:  msetzu
  linkedin_username: mattia-setzu-062b01158

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

font-awesome:
  assets: true

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
