# Site settings
title: MSetzu
description: >- # this means to ignore newlines until "baseurl:"
  Explaining the world, one model at a time.
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
author:
  email: m.setzu@outlook.com
  github_username:  msetzu
  linkedin_username: mattia-setzu-062b01158

# Build settings
markdown: redcarpet
plugins_dir:
  - jekyll-feed

font-awesome:
  assets: true

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    # css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins: ['jekyll-paginate', 'jekyll-font-awesome-sass', 'jekyll-scholar']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
